workflows:
  version: 2
  build_and_test:
    jobs:
      - common:
          filters:
            branches:
              - master
      - projectA:
          filters:
            branches:
              - projectA
      - projectB:
          filters:
            branches:
              - projectB